version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database/data:/data/db
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - mint
  nginx:
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend
      - frontend
    ports:
      - 1337:443
    networks:
      - mint
  frontend:
    depends_on:
      - mongodb
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - mint
  backend:
    depends_on:
      - mongodb
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - SECRET=${SECRET}
    networks:
      - mint
    restart: on-failure
  admin-panel:
    image: zauberzeug/nicegui:latest
    ports:
      - 8080:8080
      - 8082:8082
    volumes:
      - ./admin-panel/:/app # mounting local app directory
    environment:
      - PUID=1000 # change this to your user id
      - PGID=1000 # change this to your group id
      - STORAGE_SECRET="secret"
      - SERVER_URL=http://backend:8000
    networks:
      - mint
    depends_on:
      - backend
    restart: on-failure
  mongo-express:
    restart: on-failure
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_ROOT_PASSWORD}@mongodb:27017/
    ports:
      - "8081:8081"
    networks:
      - mint
networks:
  mint:
